
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.bit_field]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.const_fn]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-deploy"

[[exemptions.multiboot2-common]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta_derive]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.uefi-raw]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.uguid]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.volatile]]
version = "0.4.6"
criteria = "safe-to-deploy"
